name: Build and push the latest build to production

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract GITHUB_REF Tag value
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push production images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${{ steps.extract_tag.outputs.tag }}
          push: true
  
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
      - uses: actions/checkout@v2
      
      - name: Helm Install
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1
          
      - name: Set AKS Context
        uses: Azure/aks-set-context@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: mslearn-gh-pipelines-30598 
          cluster-name: contoso-video
          
      - name: Run Helm Deploy
        run: |
          helm upgrade \
              --install \
              --create-namespace \
              --atomic \
              --wait \
              --debug \
              --namespace production \
              contoso-website \
              ./kubernetes/contoso-website \
              --set image.repository=${{ secrets.ACR_NAME }} \
              --set dns.name=${{ secrets.DNS_NAME }}
              --set image.tag=${GITHUB_REF##*/}