name: Build and push the tagged build to production

on:
  push:
    tags: 
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: build_push_image
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ ACR_NAME }}
          username: ${{ ACR_USERNAME }}
          password: ${{ ACR_PASSWORD }}
          
        - name: Build and push production image
          uses: docker/build-push-action@v2.6.1
          with:
            tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${GITHUB_REF#refs/tags}
            context: .
            push: true
