name: Build and push the tagged build to production

on:
  push:
    tags: 
      - 'v*'

jobs: 
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ ACR_NAME }}
          username: ${{ ACR_USERNAME }}
          password: ${{ ACR_PASSWORD }}

      - name: Build and push production image
        uses: docker/build-push-action@v2.6.1
        with:
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${GITHUB_REF#refs/tags}
          context: .
          push: true
